
language: node_js
node_js: 10
cache:
  directories:
  - node_modules
before_script:
  - npm install
script:
  - npm run build
  - cp -r static/* ./dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master